version: "3"

networks:
    dsnet:
    jenkins:


services:

    ### DEVELOPMENT ENVIRONMENT ###

    # # Mongodb database service
    mongo:
        image: mongo
        container_name: mongo
        environment:
            MONGO_INITDB_DATABASE: training_database
            # MONGO_INITDB_ROOT_USERNAME: admin
            # MONGO_INITDB_ROOT_PASSWORD: pass
        volumes:
            - mongodb:/data/db
        networks: 
            - dsnet
        ports:
            - 27017:27017
    
    # # Mongodb seeder service
    mongo_seeder:
        container_name: mongo_seeder
        build: ./1_Data/
        networks: 
            - dsnet
        depends_on:
            - mongo

    # # Mongodb management console
    # mongo-express:
    #     image: mongo-express
    #     container_name: mongo_express
    #     networks: 
    #         - dsnet
    #     ports:
    #         - 8081:8081
    #     # environment:
    #     #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    #     #     ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    #     depends_on: 
    #         - mongo

    # # Jupyter (Python) DEVelopment enviroment 
    jupyter:
        image: datascience/jupyter_lab
        container_name: jupyterlab
        build: ./2_DevLab/
        networks: 
            - dsnet
        ports:
            - 8888:8888
        volumes:
            # or ModelOps_Credit_Scoring folder depending on the demo
            # - /home/ubuntu/ModelOps_OMM:/home/jovyan/work/ModelOps_OMM
            # - ./2_DevLab/:/home/jovyan/work/2_DevLab
            # - ./:/home/jovyan/work/2_DevLab
            - c:/Users/ivnard/Desktop/MODELOPS_OMM_Churn_DEMO:/home/jovyan/work/MODELOPS_OMM_Churn_DEMO

    ### CI/CD ENVIRONMENT ###
    
    # Jenkins service
    jenkins-master:
        image: "devopslab/jenkins"
        container_name: "jenkins-blueocean"
        privileged: true
        build: ./3_CI_CD/
        ports:
          - "50000:50000"
          - "8080:8080"
        volumes:
            - "jenkins-docker-certs:/certs/client"
            - "jenkins-data:/var/jenkins_home"
            # Check the right path. Should be /home/project
            - "./:/home"
        networks: 
            - jenkins
    
    docker:
        privileged: true
        image: "docker:dind"
        container_name: "jenkins-docker"
        ports:
            - "2376:2376"
        environment: 
            - DOCKER_TLS_CERTDIR=/certs
        volumes: 
            - "jenkins-docker-certs:/certs/client"
            - "jenkins-data:/var/jenkins_home"
        networks: 
            - jenkins


volumes:
    mongodb:
    jenkins-docker-certs:
    jenkins-data: